# Generated by Django 4.2 on 2024-03-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_testimonials_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testimonials',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
