# Generated by Django 4.2 on 2024-04-03 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_currentopenings'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('resume', models.FileField(max_length=255, upload_to='Job_Applications/')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('is_selected', models.BooleanField(blank=True, default=0, null=True)),
                ('applied_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.currentopenings')),
            ],
        ),
    ]
