# Generated by Django 4.2 on 2024-04-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_city_country_state_servicelocation_city_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
    ]
