# Generated by Django 4.2 on 2024-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('Joining_date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('admin_approval', models.BooleanField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(blank=True, default=1, null=True)),
            ],
        ),
    ]
