# Generated by Django 4.2 on 2024-04-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoteam',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
