# Generated by Django 4.2 on 2024-04-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0002_cargoteam_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargoteam',
            name='admin_approval',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
