# Generated by Django 4.2 on 2024-04-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0003_alter_cargoteam_admin_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoteam',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargoteam',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cargoteam',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cargoteam',
            name='country',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cargoteam',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargoteam',
            name='state',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
