# Generated by Django 4.2 on 2024-06-30 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_notifications'),
        ('Register_Login', '0005_cargoteam_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargoteam',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.city'),
        ),
    ]
