# Generated by Django 4.2 on 2024-03-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbooking',
            name='shipment_type',
            field=models.CharField(default='Home Pickup', max_length=30),
        ),
    ]
