# Generated by Django 4.2 on 2024-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_shipmentbooking_shipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentbooking',
            name='delivery_option',
            field=models.CharField(blank=True, choices=[('road', 'By Road'), ('air', 'By Air'), ('sea', 'By Sea')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentbooking',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('speed', 'Speed')], max_length=10, null=True),
        ),
    ]
