# Generated by Django 4.2 on 2024-03-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_shipmentbooking_delivery_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentbooking',
            name='package_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
