# Generated by Django 4.2 on 2024-03-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_shipmentbooking_package_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentbooking',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentbooking',
            name='receiver_contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentbooking',
            name='sender_contact_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
