# Generated by Django 4.2 on 2024-03-13 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_shipmentbooking_contact_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentbooking',
            old_name='tracking_code',
            new_name='uid',
        ),
        migrations.AddField(
            model_name='shipmentbooking',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='shipmentbooking',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
