# Generated by Django 4.2 on 2024-05-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_shipmentbooking_booking_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentbooking',
            name='is_active',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentbooking',
            name='is_confirmed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
