# Generated by Django 4.2 on 2024-05-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0008_alter_shipmentbooking_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerIssues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issues', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('action_taken', models.BooleanField(blank=True, default=1, null=True)),
            ],
        ),
    ]
