# Generated by Django 4.2 on 2024-05-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_customerissues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerissues',
            name='action_taken',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
