# Generated by Django 4.2 on 2024-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_alter_customerissues_action_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerissues',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customerissues',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
