# Generated by Django 4.2 on 2024-05-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_customerissues_date_customerissues_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbooking',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
