# Generated by Django 4.2 on 2024-06-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0013_shipmenttracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttracking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
