# Generated by Django 4.2 on 2024-06-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0014_alter_shipmenttracking_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmenttracking',
            name='tracking_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
