# Generated by Django 4.2 on 2024-06-08 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0015_alter_shipmenttracking_tracking_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderQueries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('queries', models.TextField(blank=True, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('action_taken', models.BooleanField(blank=True, default=0, null=True)),
            ],
        ),
    ]
