# Generated by Django 4.2 on 2024-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0016_orderqueries'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqueries',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
