# Generated by Django 4.2 on 2024-06-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0018_shipmenttracking_delivery_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttracking',
            name='arrived_for_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='return_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('packed', 'Packed'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived_at_destination_hub', 'Arrived at Destination Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('returned', 'Returned'), ('canceled', 'Canceled'), ('delayed', 'Delayed')], default='processing', max_length=30),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='returned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
