# Generated by Django 4.2 on 2024-06-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0019_shipmenttracking_arrived_for_return_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttracking',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
