# Generated by Django 4.2 on 2024-07-01 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_notifications'),
        ('Customer', '0020_shipmenttracking_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentbooking',
            name='shipping_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.city'),
        ),
    ]
