# Generated by Django 4.2 on 2024-07-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_shipmentbooking_shipping_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttracking',
            name='return_shipped_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
