# Generated by Django 4.2 on 2024-07-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0022_shipmenttracking_return_shipped_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttracking',
            name='destination_hub_return_arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
