# Generated by Django 4.2 on 2024-07-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0023_shipmenttracking_destination_hub_return_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenttracking',
            name='current_return_location',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
