# Generated by Django 4.2 on 2024-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0024_shipmenttracking_current_return_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmenttracking',
            name='last_updated',
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='last_updated_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shipmenttracking',
            name='last_updated_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
