# Generated by Django 4.2 on 2024-07-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0025_remove_shipmenttracking_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderqueries',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
